<?php

if (!class_exists('Upfront_Presets_Server')) {
	require_once Upfront::get_root_dir() . '/library/servers/class_upfront_presets_server.php';
}

class Upfront_Login_Presets_Server extends Upfront_Presets_Server {

	private static $instance;

	public function get_element_name() {
		return 'login';
	}

	public static function serve () {
		self::$instance = new self;
		self::$instance->_add_hooks();
		add_filter( 'get_element_preset_styles', array(self::$instance, 'get_preset_styles_filter')) ;
	}

	public static function get_instance() {
		return self::$instance;
	}

	public function get_preset_styles_filter($style) {
		$style .= ' ' . self::$instance->get_presets_styles();
		return $style;
	}

	/**
	 * @return array saved presets
	 */
	public function get_presets() {
		$presets = parent::get_presets();

		return $presets;
	}

	protected function get_style_template_path() {
		return realpath(Upfront::get_root_dir() . '/elements/upfront-login/tpl/preset-style.html');
	}

	public static function get_preset_defaults() {
		return array(
			'part_style' => 'form_wrapper',
			'form_wrapper_use_border' => '',
			'form_wrapper_border_width' => 1,
			'form_wrapper_border_type' => 'solid',
			'form_wrapper_border_color' => 'rgb(0, 0, 0)',
			'form_wrapper_use_radius' => '',
			'form_wrapper_border_radius_lock' => 'yes',
			'form_wrapper_radius' => '',
			'form_wrapper_radius_number' => '',
			'form_wrapper_border_radius1' => 5,
			'form_wrapper_border_radius2' => 5,
			'form_wrapper_border_radius3' => 5,
			'form_wrapper_border_radius4' => 5,
			'field_labels_font_face' => 'Arial',
			'field_labels_font_style' => '400 normal',
			'field_labels_weight' => '400',
			'field_labels_style' => 'normal',
			'field_labels_font_size' => 14,
			'field_labels_line_height' => 1,
			'field_labels_color' => 'rgb(0, 0, 0)',
			'field_labels_use_typography' => '',
			'input_fields_font_face' => 'Arial',
			'input_fields_font_style' => '400 normal',
			'input_fields_weight' => '400',
			'input_fields_style' => 'normal',
			'input_fields_font_size' => 14,
			'input_fields_line_height' => 1,
			'input_fields_color' => 'rgb(0, 0, 0)',
			'input_fields_use_typography' => '',
			'input_fields_use_border' => '',
			'input_fields_border_width' => 1,
			'input_fields_border_type' => 'solid',
			'input_fields_border_color' => 'rgb(0, 0, 0)',
			'input_fields_use_radius' => '',
			'input_fields_border_radius_lock' => 'yes',
			'input_fields_radius' => '',
			'input_fields_radius_number' => '',
			'input_fields_border_radius1' => 5,
			'input_fields_border_radius2' => 5,
			'input_fields_border_radius3' => 5,
			'input_fields_border_radius4' => 5,
			'button_font_face' => 'Arial',
			'button_font_style' => '400 normal',
			'button_weight' => '400',
			'button_style' => 'normal',
			'button_font_size' => 14,
			'button_line_height' => 1,
			'button_color' => 'rgb(0, 0, 0)',
			'button_use_typography' => '',
			'button_use_border' => '',
			'button_border_width' => 1,
			'button_border_type' => 'solid',
			'button_border_color' => 'rgb(0, 0, 0)',
			'button_use_radius' => '',
			'button_border_radius_lock' => 'yes',
			'button_radius' => '',
			'button_radius_number' => '',
			'button_border_radius1' => 5,
			'button_border_radius2' => 5,
			'button_border_radius3' => 5,
			'button_border_radius4' => 5,
			'lost_password_text_font_face' => 'Arial',
			'lost_password_text_font_style' => '400 normal',
			'lost_password_text_weight' => '400',
			'lost_password_text_style' => 'normal',
			'lost_password_text_font_size' => 14,
			'lost_password_text_line_height' => 1,
			'lost_password_text_color' => 'rgb(0, 0, 0)',
			'lost_password_text_use_typography' => '',
			'login_trigger_font_face' => 'Arial',
			'login_trigger_font_style' => '400 normal',
			'login_trigger_weight' => '400',
			'login_trigger_style' => 'normal',
			'login_trigger_font_size' => 14,
			'login_trigger_line_height' => 1,
			'login_trigger_color' => 'rgb(0, 0, 0)',
			'login_trigger_use_typography' => '',
			'login_trigger_use_border' => '',
			'login_trigger_border_width' => 1,
			'login_trigger_border_type' => 'solid',
			'login_trigger_border_color' => 'rgb(0, 0, 0)',
			'login_trigger_use_radius' => '',
			'login_trigger_border_radius_lock' => 'yes',
			'login_trigger_radius' => '',
			'login_trigger_radius_number' => '',
			'login_trigger_border_radius1' => 5,
			'login_trigger_border_radius2' => 5,
			'login_trigger_border_radius3' => 5,
			'login_trigger_border_radius4' => 5,
			'logout_link_font_face' => 'Arial',
			'logout_link_font_style' => '400 normal',
			'logout_link_weight' => '400',
			'logout_link_style' => 'normal',
			'logout_link_font_size' => 14,
			'logout_link_line_height' => 1,
			'logout_link_color' => 'rgb(0, 0, 0)',
			'logout_link_use_typography' => '',
			'logout_link_use_border' => '',
			'logout_link_border_width' => 1,
			'logout_link_border_type' => 'solid',
			'logout_link_border_color' => 'rgb(0, 0, 0)',
			'logout_link_use_radius' => '',
			'logout_link_border_radius_lock' => 'yes',
			'logout_link_radius' => '',
			'logout_link_radius_number' => '',
			'logout_link_border_radius1' => 5,
			'logout_link_border_radius2' => 5,
			'logout_link_border_radius3' => 5,
			'logout_link_border_radius4' => 5,
			'field_labels_font_face_hover' => 'Arial',
			'field_labels_font_style_hover' => '400 normal',
			'field_labels_weight_hover' => '400',
			'field_labels_style_hover' => 'normal',
			'field_labels_font_size_hover' => 14,
			'field_labels_line_height_hover' => 1,
			'field_labels_color_hover' => 'rgb(0, 0, 0)',
			'field_labels_use_typography_hover' => '',
			'input_fields_font_face_hover' => 'Arial',
			'input_fields_font_style_hover' => '400 normal',
			'input_fields_weight_hover' => '400',
			'input_fields_style_hover' => 'normal',
			'input_fields_font_size_hover' => 14,
			'input_fields_line_height_hover' => 1,
			'input_fields_color_hover' => 'rgb(0, 0, 0)',
			'input_fields_use_typography_hover' => '',
			'input_fields_use_border_hover' => '',
			'input_fields_border_width_hover' => 1,
			'input_fields_border_type_hover' => 'solid',
			'input_fields_border_color_hover' => 'rgb(0, 0, 0)',
			'input_fields_use_radius_hover' => '',
			'input_fields_border_radius_lock_hover' => 'yes',
			'input_fields_radius_hover' => '',
			'input_fields_radius_number_hover' => '',
			'input_fields_border_radius1_hover' => 5,
			'input_fields_border_radius2_hover' => 5,
			'input_fields_border_radius3_hover' => 5,
			'input_fields_border_radius4_hover' => 5,
			'button_font_face_hover' => 'Arial',
			'button_font_style_hover' => '400 normal',
			'button_weight_hover' => '400',
			'button_style_hover' => 'normal',
			'button_font_size_hover' => 14,
			'button_line_height_hover' => 1,
			'button_color_hover' => 'rgb(0, 0, 0)',
			'button_use_typography_hover' => '',
			'button_use_border_hover' => '',
			'button_border_width_hover' => 1,
			'button_border_type_hover' => 'solid',
			'button_border_color_hover' => 'rgb(0, 0, 0)',
			'button_use_radius_hover' => '',
			'button_border_radius_lock_hover' => 'yes',
			'button_radius_hover' => '',
			'button_radius_number_hover' => '',
			'button_border_radius1_hover' => 5,
			'button_border_radius2_hover' => 5,
			'button_border_radius3_hover' => 5,
			'button_border_radius4_hover' => 5,
			'lost_password_text_font_face_hover' => 'Arial',
			'lost_password_text_font_style_hover' => '400 normal',
			'lost_password_text_weight_hover' => '400',
			'lost_password_text_style_hover' => 'normal',
			'lost_password_text_font_size_hover' => 14,
			'lost_password_text_line_height_hover' => 1,
			'lost_password_text_color_hover' => 'rgb(0, 0, 0)',
			'lost_password_text_use_typography_hover' => '',
			'login_trigger_font_face_hover' => 'Arial',
			'login_trigger_font_style_hover' => '400 normal',
			'login_trigger_weight_hover' => '400',
			'login_trigger_style_hover' => 'normal',
			'login_trigger_font_size_hover' => 14,
			'login_trigger_line_height_hover' => 1,
			'login_trigger_color_hover' => 'rgb(0, 0, 0)',
			'login_trigger_use_typography_hover' => '',
			'login_trigger_use_border_hover' => '',
			'login_trigger_border_width_hover' => 1,
			'login_trigger_border_type_hover' => 'solid',
			'login_trigger_border_color_hover' => 'rgb(0, 0, 0)',
			'login_trigger_use_radius_hover' => '',
			'login_trigger_border_radius_lock_hover' => 'yes',
			'login_trigger_radius_hover' => '',
			'login_trigger_radius_number_hover' => '',
			'login_trigger_border_radius1_hover' => 5,
			'login_trigger_border_radius2_hover' => 5,
			'login_trigger_border_radius3_hover' => 5,
			'login_trigger_border_radius4_hover' => 5,
			'logout_link_font_face_hover' => 'Arial',
			'logout_link_font_style_hover' => '400 normal',
			'logout_link_weight_hover' => '400',
			'logout_link_style_hover' => 'normal',
			'logout_link_font_size_hover' => 14,
			'logout_link_line_height_hover' => 1,
			'logout_link_color_hover' => 'rgb(0, 0, 0)',
			'logout_link_use_typography_hover' => '',
			'logout_link_use_border_hover' => '',
			'logout_link_border_width_hover' => 1,
			'logout_link_border_type_hover' => 'solid',
			'logout_link_border_color_hover' => 'rgb(0, 0, 0)',
			'logout_link_use_radius_hover' => '',
			'logout_link_border_radius_lock_hover' => 'yes',
			'logout_link_radius_hover' => '',
			'logout_link_radius_number_hover' => '',
			'logout_link_border_radius1_hover' => 5,
			'logout_link_border_radius2_hover' => 5,
			'logout_link_border_radius3_hover' => 5,
			'logout_link_border_radius4_hover' => 5,
			'field_labels_font_face_focus' => 'Arial',
			'field_labels_font_style_focus' => '400 normal',
			'field_labels_weight_focus' => '400',
			'field_labels_style_focus' => 'normal',
			'field_labels_font_size_focus' => 14,
			'field_labels_line_height_focus' => 1,
			'field_labels_color_focus' => 'rgb(0, 0, 0)',
			'field_labels_use_typography_focus' => '',
			'input_fields_font_face_focus' => 'Arial',
			'input_fields_font_style_focus' => '400 normal',
			'input_fields_weight_focus' => '400',
			'input_fields_style_focus' => 'normal',
			'input_fields_font_size_focus' => 14,
			'input_fields_line_height_focus' => 1,
			'input_fields_color_focus' => 'rgb(0, 0, 0)',
			'input_fields_use_typography_focus' => '',
			'input_fields_use_border_focus' => '',
			'input_fields_border_width_focus' => 1,
			'input_fields_border_type_focus' => 'solid',
			'input_fields_border_color_focus' => 'rgb(0, 0, 0)',
			'input_fields_use_radius_focus' => '',
			'input_fields_border_radius_lock_focus' => 'yes',
			'input_fields_radius_focus' => '',
			'input_fields_radius_number_focus' => '',
			'input_fields_border_radius1_focus' => 5,
			'input_fields_border_radius2_focus' => 5,
			'input_fields_border_radius3_focus' => 5,
			'input_fields_border_radius4_focus' => 5,
			'button_font_face_focus' => 'Arial',
			'button_font_style_focus' => '400 normal',
			'button_weight_focus' => '400',
			'button_style_focus' => 'normal',
			'button_font_size_focus' => 14,
			'button_line_height_focus' => 1,
			'button_color_focus' => 'rgb(0, 0, 0)',
			'button_use_typography_focus' => '',
			'button_use_border_focus' => '',
			'button_border_width_focus' => 1,
			'button_border_type_focus' => 'solid',
			'button_border_color_focus' => 'rgb(0, 0, 0)',
			'button_use_radius_focus' => '',
			'button_border_radius_lock_focus' => 'yes',
			'button_radius_focus' => '',
			'button_radius_number_focus' => '',
			'button_border_radius1_focus' => 5,
			'button_border_radius2_focus' => 5,
			'button_border_radius3_focus' => 5,
			'button_border_radius4_focus' => 5,
			'lost_password_text_font_face_focus' => 'Arial',
			'lost_password_text_font_style_focus' => '400 normal',
			'lost_password_text_weight_focus' => '400',
			'lost_password_text_style_focus' => 'normal',
			'lost_password_text_font_size_focus' => 14,
			'lost_password_text_line_height_focus' => 1,
			'lost_password_text_color_focus' => 'rgb(0, 0, 0)',
			'lost_password_text_use_typography_focus' => '',
			'login_trigger_font_face_focus' => 'Arial',
			'login_trigger_font_style_focus' => '400 normal',
			'login_trigger_weight_focus' => '400',
			'login_trigger_style_focus' => 'normal',
			'login_trigger_font_size_focus' => 14,
			'login_trigger_line_height_focus' => 1,
			'login_trigger_color_focus' => 'rgb(0, 0, 0)',
			'login_trigger_use_typography_focus' => '',
			'login_trigger_use_border_focus' => '',
			'login_trigger_border_width_focus' => 1,
			'login_trigger_border_type_focus' => 'solid',
			'login_trigger_border_color_focus' => 'rgb(0, 0, 0)',
			'login_trigger_use_radius_focus' => '',
			'login_trigger_border_radius_lock_focus' => 'yes',
			'login_trigger_radius_focus' => '',
			'login_trigger_radius_number_focus' => '',
			'login_trigger_border_radius1_focus' => 5,
			'login_trigger_border_radius2_focus' => 5,
			'login_trigger_border_radius3_focus' => 5,
			'login_trigger_border_radius4_focus' => 5,
			'logout_link_font_face_focus' => 'Arial',
			'logout_link_font_style_focus' => '400 normal',
			'logout_link_weight_focus' => '400',
			'logout_link_style_focus' => 'normal',
			'logout_link_font_size_focus' => 14,
			'logout_link_line_height_focus' => 1,
			'logout_link_color_focus' => 'rgb(0, 0, 0)',
			'logout_link_use_typography_focus' => '',
			'logout_link_use_border_focus' => '',
			'logout_link_border_width_focus' => 1,
			'logout_link_border_type_focus' => 'solid',
			'logout_link_border_color_focus' => 'rgb(0, 0, 0)',
			'logout_link_use_radius_focus' => '',
			'logout_link_border_radius_lock_focus' => 'yes',
			'logout_link_radius_focus' => '',
			'logout_link_radius_number_focus' => '',
			'logout_link_border_radius1_focus' => 5,
			'logout_link_border_radius2_focus' => 5,
			'logout_link_border_radius3_focus' => 5,
			'logout_link_border_radius4_focus' => 5,
			'id' => 'default',
			'name' => self::$instance->get_l10n('default_preset')
		);
	}
}

Upfront_Login_Presets_Server::serve();
